### PR TITLE
std::atomic support

### LINKED ISSUE #50: std::atomic support

### PR DESCRIPTION
**Pull request by VelocityRa**
Resolves #50.
Previous PR: #53.

### CODE REVIEW

**Comment by fraillt** [comment]
Thank you ;)

Answering your question in #50 about setting up a test framework, at least on ubuntu/debian its super easy.
Simply install it with the system package manager:
```bash
apt-get install libgmock-dev
```

**Comment by VelocityRa** [comment]
Done, ready for review.

**Comment by VelocityRa** [comment]
Bump.

**Comment by fraillt** [comment]
thank you!

**Pull request merged**
