### PR TITLE
Integer casts. Part 2.

### PR DESCRIPTION
**Pull request by tower120**
Shame on me, but I don't want to install GTest on my windows local machine...
I'll use your CI instead. Bear with me.
WIP.

### CODE REVIEW

**Comment by fraillt** [comment]
Ok, no problem:)

**Comment by tower120** [comment]
Look at `OutputAdapterBitPackingWrapper::writeBitsInternal(const T &v, size_t size)` : 
```cpp
            template<typename T>
            void writeBitsInternal(const T &v, size_t size) {
                constexpr size_t valueSize = details::BitsSize<UnsignedType>::value;
                auto value = v;
                auto bitsLeft = size;
                while (bitsLeft > 0) {
                    auto bits = (std::min)(bitsLeft, valueSize);
                    _scratch |= static_cast<ScratchType>( value ) << _scratchBits;
                    _scratchBits += bits;
                    if (_scratchBits >= valueSize) {
                        auto tmp = static_cast<UnsignedType>(_scratch & _MASK);
                        this->_wrapped.template writeBytes<sizeof(UnsignedType), UnsignedType >(tmp);
                        _scratch >>= valueSize;
                        _scratchBits -= valueSize;

                        value >>= valueSize;
                    }
                    bitsLeft -= bits;
                }
            }
```

Here `_scratch` is `uint16_t` . For bitshift operation it implicitly converted to register-friendly int:
http://coliru.stacked-crooked.com/a/e19c71a43bba6904

Moreover right-bitshift on signed "implementation defined" https://stackoverflow.com/a/7636 .

So... How should I fix that?
Convert `_scratch` to machine-friendly unsigned int (not size_t), do bit operation, then convert back to ScratchType(uint16_t):
```cpp
_scratch = static_cast<ScratchType>(static_cast<unsigned int>(_scratch) >> valueSize);
```
?

**Comment by fraillt** [comment]
I can't try it now, but maybe uint_fast16t would work, instead of uint_16t?

**Comment by tower120** [comment]
`uint_fast16_t` works. So you want just to change ScratchType to it, or cast to it? 
I didn't dig enough in OutputAdapterBitPackingWrapper logic.

**Comment by fraillt** [comment]
Yes, you can change ScratchType to it, thank you!

**Comment by tower120** [comment]
Just to be sure.
Here:
```cpp
        template<typename T, typename std::enable_if<std::is_floating_point<T>::value>::type * = nullptr>
        details::SameSizeUnsigned<T> getRangeValue(const T &v, const RangeSpec<T> &r) {
            using VT = details::SameSizeUnsigned<T>;
            const VT maxUint = (static_cast<VT>(1) << r.bitsRequired) - 1;
            const auto ratio = (v - r.min) / (r.max - r.min);
            return static_cast<VT>(ratio * maxUint);
        }
```

You expect ratio to be integer or float?

**Comment by tower120** [comment]
Now this.
```cpp
            template<typename T>
            void readBitsInternal(T &v, size_t size) {
                auto bitsLeft = size;
                T res{};
                while (bitsLeft > 0) {
                    auto bits = (std::min)(bitsLeft, details::BitsSize<UnsignedValue>::value);
                    if (m_scratchBits < bits) {
                        UnsignedValue tmp;
                        this->_wrapped.template readBytes<sizeof(UnsignedValue), UnsignedValue>(tmp);
                        m_scratch |= static_cast<ScratchType>(tmp) << m_scratchBits;
                        m_scratchBits += details::BitsSize<UnsignedValue>::value;
                    }
                    auto shiftedRes =
                        static_cast<T>(m_scratch & ((static_cast<ScratchType>(1) << bits) - 1)) << (size - bitsLeft);
                    res |= shiftedRes;
                    m_scratch >>= bits;
                    m_scratchBits -= bits;
                    bitsLeft -= bits;
                }
                v = res;
            }
```
```
/home/travis/build/fraillt/bitsery/include/bitsery/deserializer.h:144:25: error: conversion to ‘unsigned char’ from ‘int’ may alter its value [-Werror=conversion]

                     res |= shiftedRes;
```

**Comment by fraillt** [comment]
Maybe it should be like this: `res |= static_cast<T>(shiftedRes);`

**Comment by tower120** [comment]
Nah, shifted res already T:
```cpp
auto shiftedRes = static_cast<T>(...);
```
The thing is - when T are small sized (like uint16_t), compiler convert it to int, do the things, then convert back. 
I can do this, instead:
```cpp
 res = static_cast<T>(res | shiftedRes);
```

**Comment by tower120** [comment]
```cpp
        template<typename TValue>
        TValue swap(TValue value) {
            constexpr size_t TSize = sizeof(TValue);
            using UT = typename std::conditional<TSize == 1, uint8_t,
                    typename std::conditional<TSize == 2, uint16_t,
                            typename std::conditional<TSize == 4, uint32_t, uint64_t>::type>::type>::type;
            return SwapImpl::exec(static_cast<UT>(value));
        }
```
`SwapImpl::exec() -> uint64_t`, while TValue - signed. Are you sure about this? That bytes reorder works correctly for signed too?

**Comment by tower120** [comment]
You need to see and fix errors in `compact_value.h` yourself. That's something that I'm not completely understand.
Grab my branch - fix them, and I'll proceed.

**Comment by fraillt** [comment]
Thanks for your work,
I just merge it to develop now, and try to fix warnings with compact_value and push back to develop, I'll inform when its done.

**Pull request merged**
